import type { NextPage } from "next";
import Head from "next/head";
import { Footer } from "../components/Footer";
import { Header } from "../components/Header";
import { Main } from "./Main";

const Home: NextPage = () => {
  return (
    <div className="container">
      <Head>
        <title>WebperfIst</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main /> 

      {/* <Footer /> */}
    </div>
  );
};

export default Home;
